// Re-export all types
export * from './types';

// Re-export validators (excluding conflicting type names)
export {
  // Schemas
  PlanSchema,
  UserRoleSchema,
  GenderSchema,
  ConsultationStatusSchema,
  AppointmentTypeSchema,
  AppointmentStatusSchema,
  FileTypeSchema,
  AddressSchema,
  AllergySchema,
  ChronicConditionSchema,
  CurrentMedicationSchema,
  EmergencyContactSchema,
  CreatePatientSchema,
  UpdatePatientSchema,
  CreateUserSchema,
  UpdateUserSchema,
  TemplateFieldTypeSchema,
  TemplateFieldSchema,
  CreateTemplateSchema,
  UpdateTemplateSchema,
  CreateAppointmentSchema,
  UpdateAppointmentSchema,
  VitalSignsSchema,
  SOAPNotesSchema,
  DiagnosisSchema,
  CreateConsultationSchema,
  UpdateConsultationSchema,
  PrescriptionMedicationSchema,
  CreatePrescriptionSchema,
  TranscriptionRequestSchema,
  StructuredNoteRequestSchema,
  PaginationSchema,
  SearchSchema,
  // Inferred types from validators
  type CreatePatient,
  type UpdatePatient,
  type CreateUser,
  type UpdateUser,
  type CreateTemplate,
  type UpdateTemplate,
  type CreateAppointment,
  type UpdateAppointment,
  type CreateConsultation,
  type UpdateConsultation,
  type CreatePrescription,
  type Pagination,
  type Search,
} from './validators';
